### ISSUE TITLE
After latest update lg-remote-control custom card not showing anymore

### ISSUE THREAD

**Issue by MEKadan** [madmicio/LG-WebOS-Remote-Control#130]
This has been working OK until yesterday, now I get this:

![image](https://github.com/madmicio/LG-WebOS-Remote-Control/assets/66167932/0c3c187d-0e74-4217-8571-166e3677076a)

Where should I start looking for problam?

**Comment by MEKadan** [comment]
Hmm.. There was an older thread started 3 weeks ago describing the same problem: https://github.com/madmicio/LG-WebOS-Remote-Control/issues/126

Because the error occurred only after yesterday I thought it would be different case, however, the fix mentioned there,, editing the resource string worked.

The resource string should be:

`hacsfiles/LG-WebOS-Remote-Control/lg-remote-control.js?hacstag=25700599020`

**Comment by gregorasia** [comment]
> This has been working OK until yesterday, now I get this:
> 
> ![image](https://user-images.githubusercontent.com/66167932/282881951-0c3c187d-0e74-4217-8571-166e3677076a.png)
> 
> Where should I start looking for problam?

It's exactly the same for me.

**Comment by Clam58** [comment]
If you update to version 2.0.1 the resource resets to null, so you need to manual re-edit to fix. Hopefully @madmicio can fix this in due course.

**Comment by MEKadan** [comment]
> If you update to version 2.0.1 the resource resets to null, so you need to manual re-edit to fix. Hopefully @madmicio can fix this in due course.


The point is, that it still shows the error even after manually updating the resource string.  The module works, though.

**Comment by twanjaarsveld** [comment]
having the same error will try the resource fix

```
Custom element doesn't exist: lg-remote-control.
type: custom:lg-remote-control
entity: media_player.lg_tv_webos
```

**Comment by hunorbatori** [comment]
> > If you update to version 2.0.1 the resource resets to null, so you need to manual re-edit to fix. Hopefully @madmicio can fix this in due course.
> 
> The point is, that it still shows the error even after manually updating the resource string. The module works, though.

I guess because HACS for some reason thinks tha path should be `/hacsfiles/LG-WebOS-Remote-Control/**null**?hacstag=257005990201` instead of `/hacsfiles/LG-WebOS-Remote-Control/lg-remote-control.js?hacstag=257005990201` this showing the error. 

I think after the manual edit, the HACS error message safely can be ignored while the issue is not fixed.

**Comment by PhilippeP62** [comment]
Same problem , same fix (thanks) , same result

**Comment by rozPierog** [comment]
I had to change resource path to lg remote inside `http://homeassistant.local:<port>/config/lovelace/resources` to the one provided here https://github.com/madmicio/LG-WebOS-Remote-Control#hacs-card-install

**Comment by CarlesLlobet** [comment]
+1 ! 
Same problem, same "fix" (workaround), same result.

Looks like HACS is not finding the js file properly (hence the "null")? Maybe something related to a HACS update on their syntax for modules?

**Comment by cstosgale** [comment]
I was attempting to fix exactly this issue by removing that line, as I thought it worked the opposite way round. I've been having this issue since before that commit, but it doesn't seem to have made any difference

**Comment by CarlesLlobet** [comment]
Oh I see @cstosgale. Apologies.
Actually although it should not (and does not) make any difference according to [the docs](https://hacs.xyz/docs/publish/start/#hacsjson), your attempt was quite good since I've been checking many other integrations I use such as [Transmission-card](https://github.com/amaximus/transmission-card/blob/main/hacs.json), [Alarmo-card](https://github.com/nielsfaber/alarmo-card/blob/main/hacs.json), or [mini-graph-card](https://github.com/kalkih/mini-graph-card/blob/master/hacs.json) and none of them specify "content_in_root".

I've been trying to review commits before that to see if anything could have affected the HACS install but I haven't been able to find anything else (don't know this integration's code that well).

Let's pray you guys can find it eventually 🙏

**Comment by LordMrcS** [comment]
downgrading to 1.1.3 seems easier and that fixed it for now to me. (tried 2.0, no luck there aswell)
